### ISSUE TITLE
POST-INSTALLATION 

### ISSUE THREAD

**Issue by 4msamir** [rancher/harvester-installer#37]
Is it possible to have the option of adding commands to run on the system once the installation is complete, it will helpful to have it with https://github.com/rancher/harvester-installer/pull/33 in my use case this will be a callback to provisioner so i can remove the iPXE script as all my bare-metal configure to look for network boot first and without remove the iPXE script the machine will keep loop in the installation stage.

**Comment by guangbochen** [comment]
move this to https://github.com/rancher/harvester/issues/469
