### ISSUE TITLE
can't join the k3s cluster after promote an agent node to server node

### ISSUE THREAD

**Issue by futuretea** [rancher/harvester-installer#8]
I'm trying to promote an agent node by these commands:
```bash
sudo sed -i "s/command_args=\"agent/command_args=\"server/g" /etc/init.d/k3s-service
sudo /etc/init.d/k3s-service restart
```
but after do that, this node's status can't become Ready, check /var/log/k3s-service.log, errors reported as follows:
```bash
time="2020-11-22T03:10:25.695164274Z" level=info msg="Starting k3s v1.18.9+k3s1 (630bebf9)"
time="2020-11-22T03:10:25.793658747Z" level=fatal msg="starting kubernetes: preparing server: https://10.5.3.134:6443/v1-k3s/server-bootstrap: 403 Forbidden"
time="2020-11-22T03:10:31.689770648Z" level=info msg="Starting k3s v1.18.9+k3s1 (630bebf9)"
time="2020-11-22T03:10:31.778964598Z" level=fatal msg="starting kubernetes: preparing server: https://10.5.3.134:6443/v1-k3s/server-bootstrap: 403 Forbidden"
time="2020-11-22T03:10:37.699735384Z" level=info msg="Starting k3s v1.18.9+k3s1 (630bebf9)"
time="2020-11-22T03:10:37.786083390Z" level=fatal msg="starting kubernetes: preparing server: https://10.5.3.134:6443/v1-k3s/server-bootstrap: 403 Forbidden"
time="2020-11-22T03:10:43.705767537Z" level=info msg="Starting k3s v1.18.9+k3s1 (630bebf9)"
time="2020-11-22T03:10:43.799993533Z" level=fatal msg="starting kubernetes: preparing server: https://10.5.3.134:6443/v1-k3s/server-bootstrap: 403 Forbidden"
time="2020-11-22T03:10:49.715082958Z" level=info msg="Starting k3s v1.18.9+k3s1 (630bebf9)"

```
add "-- cluster-init" to the start option for the first server in /etc/init.d/k3s-service
```bash
k3s.io/node-args: '["server","--cluster-init","--disable","local-storage","--flannel-backend","none","--node-label","k3os.io/mode","local","--node-label","k3os.io/version","v0.11.1-2-g0c73235-dirty"]'
```
restart k3s both server and agent again, the agent node become server and ready
```bash
k3os-6055 [~]$ k3s kubectl get node
NAME         STATUS   ROLES    AGE   VERSION
k3os-18411   Ready    master   45m   v1.18.9+k3s1
k3os-6055    Ready    master   64m   v1.18.9+k3s1
```

**Comment by futuretea** [comment]
![image](https://user-images.githubusercontent.com/15064560/99926579-2cc1ea80-2d7d-11eb-9c49-23b8faec675e.png)

**Comment by futuretea** [comment]
I tried to add a second k3s server through the installer，the second k3s server present same error.

**Comment by srbala** [comment]
@futuretea You may be using the older version of K3S for `ha-embedded` support, can you try `v1.19.5+k3s1` or later?

> NOTICE:
K3s has added full support for embedded etcd as of release v1.19.5+k3s1. Versions v1.19.1 thru v1.19.4 provide only experimental support for embedded etcd. Embedded etcd replaced experimental Dqlite in the K3s v1.19.1 release. This is a breaking change. Please note that upgrades from experimental Dqlite to embedded etcd are not supported. If you attempt an upgrade it will not succeed and data will be lost.

**Comment by futuretea** [comment]
@srbala Thanks, k3os 1.19.5-rc1 (k3s v1.19.5+k3s2) is work.

**Comment by srbala** [comment]
@futuretea thanks for the update. Since the documented version is working, please close this issue

**Comment by futuretea** [comment]
@srbala Because of this issue is about the `harvester-installer`, I'd like to keep this issue open until the installer dump k3os version and  add  args `--cluster-init` to first server.

**Comment by guangbochen** [comment]
close in favor https://github.com/rancher/harvester-installer/pull/29
